name: GitHub Actions

on:
  push:
    branches:
    - test2

jobs:
  test:
    name: CUDA
    runs-on: [self-hosted, linux]
    timeout-minutes: 60
    strategy:
      fail-fast: false
    steps:
      - name: Cleanup
        run: sudo rm -rf $GITHUB_WORKSPACE
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 5
          submodules: true
      - name: Test CUDA
        shell: bash
        run: |
          distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
          curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
          curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
          lspci -vnn | grep -i VGA -A 12
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y curl nvidia-docker2
          sudo systemctl restart docker
          nvidia-smi
          sudo docker run -e TASK=cuda -e COMPILER=gcc -e GITHUB_ACTIONS=true -e OS_NAME=linux -e BUILD_DIRECTORY="/LightGBM" -e CONDA_ENV="test-env" -v "$GITHUB_WORKSPACE":"/LightGBM" --rm --gpus all nvidia/cuda:10.0-devel /bin/bash -c 'export CONDA="$HOME/miniconda" && export PATH="$CONDA/bin:${HOME}/.local/bin:$PATH" && apt-get update && apt-get install --no-install-recommends -y curl wget build-essential && curl -sL https://cmake.org/files/v3.18/cmake-3.18.1-Linux-x86_64.sh -o cmake.sh && chmod +x cmake.sh && ./cmake.sh --prefix=/usr/local --exclude-subdir && rm cmake.sh && nvidia-smi && /LightGBM/.ci/setup.sh && /LightGBM/.ci/test.sh'
